# Configuration for SE Letters project

# API Configuration
api:
  xai:
    base_url: "https://api.x.ai/v1"
    model: "grok-3-latest"
    api_key: "xai-RPhTjf3SzTbm11ZKcpFV0hsOqVTSj8QUbTFhUrrQWaE"
    max_tokens: 4096
    temperature: 0.1
    timeout: 30

data:
  input:
    letters_directory: "data/input/letters/PSIBS_MODERNIZATION/07_ PWP communication letters & SLA"
    excel_file: "data/input/letters/IBcatalogue.xlsx"
    supported_formats:
      - ".pdf"
      - ".docx"
      - ".doc"
  
  output:
    json_directory: "data/output/json"
    excel_output: "data/output/matched_results.xlsx"
    logs_directory: "logs"
  
  temp:
    temp_directory: "data/temp"
    cleanup_on_exit: true
    
  # Additional configurations for IBcatalogue.xlsx
  excel_sheet: "OIC_out"
  test_letter_file: "data/input/letters/PSIBS_MODERNIZATION/07_ PWP communication letters & SLA/20170608_PIX-DC - Phase out_communication_letter-Rev00.doc"
  
  # Column mappings for IBcatalogue.xlsx
  columns:
    product_id: "PRODUCT_IDENTIFIER"
    range_name: "RANGE_LABEL"
    subrange_name: "SUBRANGE_LABEL"
    description: "PRODUCT_DESCRIPTION"
    brand: "BRAND_LABEL"
    status: "COMMERCIAL_STATUS"
    end_of_commercialization: "END_OF_COMMERCIALISATION"
    is_schneider_brand: "IS_SCHNEIDER_BRAND"
    serviceable: "SERVICEABLE"
    pl_services: "PL_SERVICES"
    bu_label: "BU_LABEL"
  
  # Processing settings
  batch_size: 50
  max_file_size_mb: 100
  
  # Filtering options
  filters:
    schneider_only: true  # Filter to Schneider Electric products only
    obsolescence_statuses:
      - "18-End of commercialisation"
      - "19-end of commercialization block"
      - "14-End of commerc. announced"

# Processing Configuration
processing:
  batch_size: 10
  max_workers: 4
  retry_attempts: 3
  retry_delay: 1.0
  
# Embedding Configuration
embedding:
  model_name: "all-MiniLM-L6-v2"
  vector_dimension: 384
  top_k_similar: 10
  similarity_threshold: 0.7

# FAISS Configuration
faiss:
  index_type: "IndexFlatL2"
  index_file: "data/temp/faiss_index.bin"
  metadata_file: "data/temp/faiss_metadata.json"

# OCR Configuration
ocr:
  tesseract_config: "--oem 3 --psm 6"
  languages: ["eng"]
  dpi: 300

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/se_letters.log"
  max_bytes: 10485760  # 10MB
  backup_count: 5

# Validation Configuration
validation:
  sample_size: 50
  confidence_threshold: 0.8
  manual_review_threshold: 0.6 